---
# The --- means we are in a YAML file
- name: "Secure server" # the name what we are going to do
  hosts: all  # all the hosts from the inventory file
  become: yes # we are becoming root to run this ansible
  become_method: sudo # to become root we are using sudo
  become_user: root # and we become root. Maybe this is not needed
  vars_files: # We specify a YAML file that contains variable. We can specify multiple files
    - become_vault.yml
  vars: # We list the variable and in this case we give the password to become root
    ansible_become_pass: "{{ become_sudo }}"
  tasks:  # the tasks, with the name and what we are going to do

    - name: "Copy secure package"
      copy:
        src: packages/secure.tar.gz
        dest: /tmp/secure.tar.gz

    - name: "extract archive"
      unarchive:
        src: /tmp/secure.tar.gz
        dest: /

    - name: "check SSH is running"
      shell: systemctl is-active --quiet sshd
      register: sshd_status
      ignore_errors: yes

    - name: "secure if ssh is running"
      shell: /usr/local/bin/secureSSHD.sh
      when: sshd_status.rc == 0


